### PR TITLE
Add multiple functions

### PR DESCRIPTION
**Pull request by Virinas-code**

### CODE REVIEW

**Comment by kraktus** [comment]
Hey @Virinas-code, not sure what this PR is about?

**Comment by Virinas-code** [comment]
It's just about adding a bunch of new clients functions, but mostly splitting all the clients over multiple files to avoid 2000+ lines file.

**Comment by benediktwerner** [comment]
Was it intentional that the PR was a draft? I didn't really look at the PR much yet since I assumed it wasn't ready yet.

I guess adding type hints caused a lot of conflicts now. Tbh it's also pretty hard to see the actual changes like this. It probably makes more sense to do the splitting into separate files in a separate PR without any other changes and then add further methods in individual PRs.

**Comment by stdolan** [comment]
@Virinas-code Are the endpoints you're keeping from this PR the External Engine endpoints from here: https://github.com/lichess-org/berserk/pull/3/commits/d2372a62c1029bff21ed1df83eb1153ed559d00a? Or are there other endpoints as part of this PR as well?

**Pull request closed without merging**
