### PR TITLE
Implement api/swiss endpoints

### PR DESCRIPTION
**Pull request by handsamtw**
1. Add all the remaining swiss endpoints:
`get_swiss_tournament_info `= `/api/swiss/{swiss_id}`
`update_swiss` = `api/swiss/{tournamentId}/edit`
`join_swiss_tournament` = `/api/swiss/{id}/join`
`get_swiss_tournament_result` = `/api/swiss/{id}/results`
`schedule_next_round` = `/api/swiss/{id}/schedule-next-round`
`terminate_swiss_tournament` = `/api/swiss/{id}/terminate`
`withdraw_swiss_tournament` = `/api/swiss/{id}/withdraw`

2. Add missing return type for tournament

### CODE REVIEW

**Comment by kraktus** [comment]
when a test break due to typing, you can use the decorator `skip_if_older_3_dot_10` instead of reverting to the old syntax, since you only need to check typing for the latest version.

**Comment by handsamtw** [comment]
> when a test break due to typing, you can use the decorator `skip_if_older_3_dot_10` instead of reverting to the old syntax, since you only need to check typing for the latest version.

Hi @kraktus , I currently use `Union` to pass, but is it recommended to use skip_if_older_3_dot_10 instead?

**Comment by kraktus** [comment]
yes, the breakage is due to pydantic, (our test framework), and not to the typing itself, so it's fine to bypass.

**Comment by kraktus** [comment]
Thanks for the numerous PRs and improvement btw! I'll need a few days to review.

**Pull request merged**
